class Constants {

  static const String isLoggedIn = 'isLoggedIn';
  static const String pass = 'pass';
  static const String user = 'user';
  static const String id = 'id';
  static const String apiKey = 'api_key';

  static const String dob = 'dob';
  static const String userType = 'userType';
  static const String apiToken = 'apiToken';
  static const String fName = 'f_name';
  static const String lName = 'l_name';
  static const String gender = 'gender';
  static const String mobile = 'mobile_no';
  static const String urlImagen = 'profile_image';
  static const String bloodGroup = 'blood_group';
  static const String token = 'token';
  static const String createdAt = 'createdAt';
  static const String updatedAt = 'updatedAt';
  static const String ultimo_acceso = 'ultimo_acceso';
  static const String data = 'data';
  static const String horario = 'horario';
  static const String festivos = 'festivos';
  static const String agenda = 'agenda';
  static const String formatoReceta = 'formatoReceta';
  static const String pass1 = 'pass1';
  static const String init = 'init';
  static const String university = 'university';
  // static const  int accesoDeAdministrador;
  static const String hospital = 'hospital';
  static const String rFC = 'rFC';
  static const String nOMBRE = 'nOMBRE';
  static const String serie = 'serie';
  static const String sello = 'sello';
  static const String noCertificado = 'noCertificado';
  static const String certificado = 'certificado';
  static const String lugarExpedicion = 'lugarExpedicion';
  static const String calle = 'calle';
  static const String noExterior = 'noExterior';
  static const String noInterior = 'noInterior';
  static const String colonia = 'colonia';
  static const String localidad = 'localidad';
  static const String municipio = 'municipio';
  static const String estado = 'estado';
  static const String pais = 'pais';
  static const String codigoPostal = 'codigoPostal';
  static const String regimen = 'regimen';
  static const String debloquear = 'debloquear';
  static const String logo = 'logo';
  static const String count = 'count';
  static const String rfc = 'rFC';
  static const String backPages = 'backPages';
  static const String alerts = 'alerts';
  static const String language_code = 'language_code';
  static const String fcmToken = 'fcmToken';
}
